### ISSUE TITLE
 issues to python program

### ISSUE THREAD

**Issue by 23bca259** [vtcbca/internal-exam-23bca259#2]
proggram 7

**Comment by 23BCA282** [comment]
here is the program in sqlite 3 
sqlite> .open emp1.db
sqlite> create table emp12
   ...> (eid int primary key,ename, dept, basic, branch);
sqlite> insert into emp12 values(1,'sajid','account',20000,'surat');
sqlite> insert into emp12 values(2,'ammar','inventory',30000,'mandvi');
sqlite> insert into emp12 values(3,'varun','it',40000,'navsari');
sqlite> insert into emp12 values(4,'ayush','hr',50000,'vyara');
sqlite> insert into emp12 values(5,'harsh','account',60000,'surat');
sqlite> .mode table
sqlite> select * from emp12;
+-----+-------+-----------+-------+---------+
| eid | ename |   dept    | basic | branch  |
+-----+-------+-----------+-------+---------+
| 1   | sajid | account   | 20000 | surat   |
| 2   | ammar | inventory | 30000 | mandvi  |
| 3   | varun | it        | 40000 | navsari |
| 4   | ayush | hr        | 50000 | vyara   |
| 5   | harsh | account   | 60000 | surat   |
+-----+-------+-----------+-------+---------+
sqlite> .mode column
sqlite> .mode csv
sqlite> .output D:\23BCA282\SQLITE3\CSV\emp12
sqlite> .output D:\23BCA282\SQLITE3\CSV\emp12.csv
sqlite>
